apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 32588

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginxa
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-nginxa
  replicas: 7
  template:
    metadata:
      labels:
        app: my-nginxa
    spec:
      containers:
      - name: my-nginxa
        image: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginxb
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-nginxb
  replicas: 7
  template:
    metadata:
      labels:
        app: my-nginxb
    spec:
      containers:
      - name: my-nginxb
        image: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginxc
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-nginxc
  replicas: 9
  template:
    metadata:
      labels:
        app: my-nginxc
    spec:
      containers:
      - name: my-nginxc
        image: nginx